/**
 * Mock data for Technician Assigned Jobs
 * Realistic air conditioning service assignments
 */

export const MOCK_JOBS = [
  {
    id: 'J-2026-011',
    customerName: 'Sarah Tan',
    customerPhone: '+65 9123 4567',
    customerEmail: 'sarah.tan@example.com',
    serviceType: 'General Servicing',
    serviceCategory: 'Maintenance',
    date: '2026-07-29',
    formattedDate: '29 Jul 2026',
    time: '09:00 AM',
    estimatedDuration: '1.5 hrs',
    status: 'In Progress',
    timeframe: 'today',
    address: '12 Jalan Bukit Ho Swee, #04-21',
    postalCode: '169566',
    unitType: '3x Daikin Inverter Split Units (R32)',
    notes: 'Quarterly general maintenance. Customer reported slight rattling sound in living room fan coil.',
    priority: 'Normal',
  },
  {
    id: 'J-2026-012',
    customerName: 'Ahmad Razali',
    customerPhone: '+65 8234 5678',
    customerEmail: 'ahmad.razali@example.com',
    serviceType: 'Gas Top-Up',
    serviceCategory: 'Refrigerant',
    date: '2026-07-29',
    formattedDate: '29 Jul 2026',
    time: '02:00 PM',
    estimatedDuration: '1 hr',
    status: 'Upcoming',
    timeframe: 'today',
    address: '88 Toa Payoh Lor 4, #08-15',
    postalCode: '310088',
    unitType: '2x Mitsubishi Electric Starmex Multi-Split',
    notes: 'Master bedroom unit blowing lukewarm air. Check pressure and top up R410A refrigerant if needed.',
    priority: 'High',
  },
  {
    id: 'J-2026-013',
    customerName: 'Priya Nair',
    customerPhone: '+65 9456 7890',
    customerEmail: 'priya.nair@example.com',
    serviceType: 'Repair Service',
    serviceCategory: 'Repair',
    date: '2026-07-30',
    formattedDate: '30 Jul 2026',
    time: '10:00 AM',
    estimatedDuration: '2 hrs',
    status: 'Upcoming',
    timeframe: 'this-week',
    address: '45 Bedok Reservoir View, #12-302',
    postalCode: '470045',
    unitType: '1x Panasonic Inverter Single-Split',
    notes: 'Water leakage reported from drainage tray. Check condensate pipe blockage and clear tray.',
    priority: 'Urgent',
  },
  {
    id: 'J-2026-014',
    customerName: 'Lina Hassan',
    customerPhone: '+65 9789 0123',
    customerEmail: 'lina.hassan@example.com',
    serviceType: 'General Servicing',
    serviceCategory: 'Maintenance',
    date: '2026-07-25',
    formattedDate: '25 Jul 2026',
    time: '11:00 AM',
    estimatedDuration: '1.5 hrs',
    status: 'Completed',
    timeframe: 'all',
    address: '210 Tampines St 23, #06-88',
    postalCode: '520210',
    unitType: '4x Mitsubishi Heavy Industries Split',
    notes: 'Completed standard chemical wash on all filters and drainage flushes. All blower fans tested OK.',
    priority: 'Normal',
  },
  {
    id: 'J-2026-015',
    customerName: 'Kelvin Lee',
    customerPhone: '+65 8112 3344',
    customerEmail: 'kelvin.lee@example.com',
    serviceType: 'Chemical Wash',
    serviceCategory: 'Deep Clean',
    date: '2026-07-31',
    formattedDate: '31 Jul 2026',
    time: '03:30 PM',
    estimatedDuration: '2.5 hrs',
    status: 'Upcoming',
    timeframe: 'this-week',
    address: '15 Bishan Street 13, #15-02',
    postalCode: '579798',
    unitType: '2x Daikin Smile Series Split Units',
    notes: 'Full chemical overhaul requested for dirty cooling coils and foul odor upon startup.',
    priority: 'Normal',
  },
  {
    id: 'J-2026-016',
    customerName: 'David Wong',
    customerPhone: '+65 9334 5566',
    customerEmail: 'david.wong@example.com',
    serviceType: 'Airflow Inspection',
    serviceCategory: 'Inspection',
    date: '2026-07-28',
    formattedDate: '28 Jul 2026',
    time: '04:00 PM',
    estimatedDuration: '1 hr',
    status: 'Completed',
    timeframe: 'this-week',
    address: '77 Marine Drive, #03-12',
    postalCode: '440077',
    unitType: '1x LG Dual Inverter Cassette',
    notes: 'Checked fan motor speed and replaced secondary air purifier filter mesh. Performance verified at 18°C.',
    priority: 'Normal',
  },
]
